#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N trimming
#
# Send an email after the job has finished
#$ -m e
#$ -M aefrainmp@protonmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load trimmomatic/0.33

#
# Write your commands in the next line

for i in *_1.fastq.gz;
	do echo
	trimmomatic PE -threads 40 -phred33 -trimlog trim.log $i "${i%_1.fastq.gz}_2.fastq.gz" \
	../data_trimmed/"${i%_1.fastq.gz}_1_trimmed.fastq.gz" ../data_trimmed/"${i%_1.fastq.gz}_1_unpaired.fastq.gz" \
	../data_trimmed/"${i%_1.fastq.gz}_2_trimmed.fastq.gz" ../data_trimmed/"${i%_1.fastq.gz}_2_unpaired.fastq.gz" \
	HEADCROP:12
done
